version: "3"

services:
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - "15432:5432"
    environment:
      DEBUG: 1
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test1234"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: Asia/Tokyo
    volumes:
      - ./dbdata/pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d